# Generated by Django 2.2 on 2021-01-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
