# Generated by Django 2.2 on 2021-01-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userform_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
